aboutme/urls.py
from django.urls import path
from django.contrib.auth import views as vistas
from aboutme import views

app_name = 'aboutme'

urlpatterns = [
    path('aboutme/', views.AboutMeView.as_view(), name="aboutme"),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('article/', views.ArticleView.as_view(), name="article"),
    path('newpost/', views.CreatPostView.as_view(), name="new_post"),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('<int:pk>/newcomment/', views.add_comment_to_post, name = 'new_comment'),
    path('comment/<int:pk>/remove', views.CommentsDeleteView.as_view(), name='comment_remove'),
    path('comment/<int:pk>/edit/', views.CommentsUpdateView.as_view(), name="comment_edit"),
    path('process_like/', views.process_like, name="process_like"),
    path('<int:pk>/reduce_like/', views.reduce_like, name="reduce_like"),
    path('print/<int:pk>', views.print_hi, name='print_hi'),
    path('<int:pk>/highlight_post/',views.highlight_post, name='highlight_post'),
    path('<int:pk>/remove_highlight', views.remove_highlight, name="remove_highlight"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from django.contrib.auth import views as vistas

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'), name="blog"),
    path('accounts/login/', vistas.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', vistas.LogoutView.as_view(template_name='blog/post_list.html'), name='logout'),
    path('', include('aboutme.urls'), name="aboutme"),
]

aboutme/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.db.models import F

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now)
    likes = models.IntegerField(default=0)
    tags = models.CharField(max_length = 50, default = '' )
    highlight = models.BooleanField(default = False)

    def highlight_post(self):
        self.highlight = True

    def remove_highlight(self):
        self.highlight = False    

    def process_likes(self):
        print(self.likes)
        self.likes += 1

    def reduce_likes(self):
        self.likes -= 1

    def split_tags(self):
        return self.tags.split()

    def get_absolute_url(self):
        return reverse('blog:post_list')

    def __str__(self):
        return self.title

class Comments(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now)

    def get_absolute_url(self):
        return reverse('blog:post_list')

comments/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from blog.models import Post, Comments

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('author', 'title', 'text', 'tags')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text' : forms.Textarea(attrs={'class': 'posttext'}),

            'tags': forms.TextInput(attrs={'class': 'form-control'}),
        }

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('text',)

        widgets = {
            'text' : forms.Textarea(attrs={'class':'comment-textarea'})
        }

        labels = {
            'text': ''
        }

aboutme/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class AboutMeView(TemplateView):
    template_name= 'aboutme/aboutme.html'

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView,)
from django.views.generic.edit import FormMixin, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from blog.models import Post, Comments
from blog.forms import PostForm, CommentsForm
from django.utils import timezone
from django.urls import reverse_lazy
from django.http import JsonResponse

# Create your views here.
class ArticleView(TemplateView):
    template_name = 'blog/article.html'


class CreatPostView(CreateView, LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'post_list.html'
    form_class = PostForm
    model = Post

class PostListView(ListView):
    model = Post
    def get_queryset(self):
        return Post.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')


class PostDetailView(DetailView, FormMixin):
    model = Post
    form_class = CommentsForm
    
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['comments_form'] = CommentsForm()
        return context
    
    

class PostUpdateView(UpdateView, LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm

    model = Post

class PostDeleteView(DeleteView, LoginRequiredMixin):
    model = Post
    success_url = reverse_lazy('blog:post_list')

class CreateCommentsView(CreateView):
    form_class = CommentsForm
    model = Comments
    

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentsForm()
    return render(request, 'blog/comments_form.html', {'form': form})

class CommentsDeleteView(DeleteView):
    model = Comments
    success_url = reverse_lazy('blog:post_list')

class CommentsUpdateView(UpdateView):
    redirect_field_name = 'blog/post_detail.html'
    form_class = CommentsForm
    model = Comments

def process_like(request):
    post_id = request.POST['post_id']
    post = Post.objects.get(id=post_id)
    post.process_likes()
    return render(request, 'blog/post_list.html')


def print_hi(request, pk):
    print('Hi there!')
    post = get_object_or_404(Post, pk=pk)
    post.process_likes()
    post.save()
    return redirect('blog:post_detail', pk=post.pk)

def reduce_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.reduce_likes()
    post.save()
    return redirect('blog:post_detail', pk=post.pk)


def highlight_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.highlight_post()
    post.save()
    return  redirect('blog:post_list')

def remove_highlight(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.remove_highlight()
    post.save()
    return  redirect('blog:post_list')

comments/views.py
from django.shortcuts import render

# Create your views here.

aboutme/templates/aboutme/aboutme.html
{% extends 'base.html'%}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'css/aboutme.css' %}">
<div class="jumbotron">
    <div class="row">
        <div class="col-12 col-lg-3 text-center">
            <img src="{% static 'img/paul.jpg' %}" style="width:292px;" alt="My photo"
                class="rounded-circle img-fluid my-photo">
        </div>
        <div class="col-12 col-lg-8 justify-content-center">
            <h3 class="display-4 text-center text-lg-left">Paul Miranda Vega</h3>
            <p class="text-justify">Hi! I'm Paul Miranda Vega, a graduated from the Universidad Autónoma de Baja
                California in
                Mexicali, Baja California from the Degree in Computational Systems. I have experience
                working with Java and JavaScript and have knowledges of Python.
                <br>
                Down below if you click on the document icon you can download my curriculum!.
            </p>
            <div class="row social-networks justify-content-center justify-content-lg-start">
                <div class="aboutme-icons">
                    <a href="https://github.com/PaulMirve"><i class="icon-github-circled"></i></a>
                    <a href="https://www.linkedin.com/in/paul-miranda-vega-28ba5b179/"><i class="icon-linkedin"></i></a>
                    <a href="https://www.facebook.com/paul.miranda.90"><i class="icon-facebook-official"></i></a>
                    <a href="{% static 'img/Curriculum.pdf' %}" download=""><i class="icon-doc"></i></a>
                </div>
            </div>
        </div>
    </div>

</div>
<div class="container">
    <h5 class="display-4">Experience</h5>
    <hr>
    <div class="row mt-5">
        <div class="col-12 col-lg-4">
            <div class="list-group" id="lista" role="tablist">
                <a href="#elemento1" class="list-group-item list-group-item-action active" data-toggle="list" role="tab"
                    aria-controls="elemento1">Xquadrone</a>
                <a href="#elemento2" class="list-group-item list-group-item-action" data-toggle="list" role="tab"
                    aria-controls="elemento2">AvanTI</a>
            </div>
        </div>
        <div class="col-12 col-lg-8 mt-lg-0 mt-3">
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="elemento1" role="tabpanel" aria-labelledBy="elemento1">
                    <p>Company in charge of innovating in the area of industrial security using drones. Working as a Java developer using Spring Boot framework fot the server and ReactJS for the client side.
                    </p>
                    <div class="row">
                        <div class="col-6">
                            <h3>Time working</h3>
                            <p>February 2019 - At present</p>
                        </div>
                        <div class="col-6">
                            <h3>Job</h3>
                            <ul>
                                <li>Junior Software Developer</li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="tab-pane fade show" id="elemento2" role="tabpanel" aria-labelledBy="elemento2">
                    <p>A escolar bussines wich objective is to develop quality software with a excelent
                        teamwork. Developers of a escolar software wich allows the profesors to update
                        the advance of temmatic content in their subjects.
                    </p>
                    <div class="row">
                        <div class="col-6">
                            <h3>Time working</h3>
                            <p>August 2018 - January 2019</p>
                        </div>
                        <div class="col-6">
                            <h3>Job</h3>
                            <ul>
                                <li>Java Programmer</li>
                                <li>Data Base Administrator</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="display-4">Technologies</h5>
    <hr>
    <div class="row mt-5">
        <div class="col-12 technologies d-flex justify-content-between"
            style="width:150px;height:150px;overflow-y:hidden;overflow-x:scroll; -webkit-overflow-scrolling: touch;">
            <img src="{% static 'img/technologies/html.png' %}" alt="HTML">
            <img src="{% static 'img/technologies/css.png' %}" alt="CSS">
            <img src="{% static 'img/technologies/bootstrap.png' %}" alt="Bootstrap">
            <img src="{% static 'img/technologies/javascript.png' %}" alt="JavaScript">
            <img src="{% static 'img/technologies/react.png' %}" alt="React">
            <img src="{% static 'img/technologies/python.png' %}" alt="Python">
            <img src="{% static 'img/technologies/django.png' %}" alt="Django">
            <img src="{% static 'img/technologies/java.png' %}" alt="Java">
            <img src="{% static 'img/technologies/springboot.png' %}" alt="Spring Boot">
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-6">
            <h5 class="display-4">Lenguages</h5>
            <hr>
            <h5>English</h5>
            <div class="progress mb-3" style="height:30px">
                <div class="progress-bar" role="progressbar" style="width:80%">80%</div>
            </div>
            <h5>Japanese</h5>
            <div class="progress mb-3" style="height:30px">
                <div class="progress-bar" role="progressbar" style="width:20%">20%</div>
            </div>
            <h3>Spanish</h3>
            <div class="progress mb-3" style="height:30px">
                <div class="progress-bar" role="progressbar" style="width:100%">Native</div>
            </div>
        </div>
        <div class="col-12 col-lg-6 ">
            <h5 class="display-4">Skills</h5>
            <hr>
            <ul>
                <li>Puntuality</li>
                <li>Responsability</li>
                <li>Teamwork</li>
            </ul>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/comments_form.html
{% load static %}
<link rel="stylesheet" href="{% static 'dist/css/medium-editor.css' %}">
<link rel="stylesheet" href="{% static 'dist/css/themes/beagle.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/fontello.css' %}">
<link rel="stylesheet" href="{% static 'css/estilos.css' %}">
<div class="container">
    <div class="row">
        <div class="col p-0">
            <form action="" method="POST">
                {%csrf_token%}
                {{ form.as_p }}
                <input type="submit" class="btn btn-comments" value="Comment">
            </form>
        </div>
    </div>
</div>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron postdetail-jumbo">
    <div class="container">
        <h3 class="display-4">{{post.title}}
            <a class="icon-link" href="{% url 'blog:print_hi' pk=post.pk %}">
                <i data-post-id="{{post.id}}" class="heart-icon icono icon-heart-empty"></i>
            </a>

        </h3>
        <p><i class="icon-calendar"></i>{{post.created_date}} <i class="icon-user"></i>{{post.author}}</p>
        {% if user.is_authenticated %}
        <a href="{% url 'blog:post_edit' pk=post.pk %}" class="btn"><i class="icon-pencil"></i> Edit</a>
        <button class="btn" data-toggle="modal" data-target="#fm-modal-grid"><i
                class="icon-trash-empty"></i>Delete</button>
        <div class="modal fade" id="fm-modal-grid" tabindex="-1" role="dialog" aria-labelledBy="fm-modal-grid"
            aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal" aria-label="Cerrar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-12 col-sm-6">
                                    <p>Are you sure you want to delte {{post.title}}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <form action="{% url 'blog:post_remove' pk=post.pk %}" method="POST">
                            {% csrf_token %}
                            <button class="btn">Delete</button>
                        </form>
                        <button class="btn btn-primary" data-dismiss="modal">Cancelar</button>

                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="d-flex justify-content-end align-content-center">
        <a class="twitter-share-button btn-sm mr-2"
            href="https://twitter.com/intent/tweet?text=http://paulmirve.pythonanywhere.com{% url 'blog:post_detail' pk=post.pk %}">
            <i class="icon-twitter mr-2"></i><b>Share</b></a>
        <div class="fb-share-button" ata-href="http://paulmirve.pythonanywhere.com{% url 'blog:post_detail' pk=post.pk%}"
            data-layout="button_count">
        </div>
    </div>

</div>
<div class="container">
    <div class="row">
        <div class="col">
            {{post.text|safe}}
        </div>
    </div>
    <hr>
    <h1>Comments</h1>
    <div class="row">
        <div class="col">
            <form action="{% url 'blog:new_comment' pk=post.pk %}" method="POST">
                {% include 'blog/comments_form.html' %}
            </form>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-12 col-lg-5">
            <ul class="list-unstyled">
                {% for comment in post.comments.all %}
                <li class="media">
                    <div class="media-body">
                        <h5 class="mt-0 mb-1">{{ comment.created_date }}</h5>
                        <p>{{ comment.text|safe|linebreaks }}</p>
                        <div class="text-right buttons">
                            <a href="{% url 'blog:comment_edit' pk=comment.pk %}" class="btn">Edit</a>
                            <form class="d-inline" action="{% url 'blog:comment_remove' pk=comment.pk %}" method="POST">
                                {% csrf_token %}
                                <a href="{% url 'blog:post_detail' pk=post.pk %}"><button
                                        class="btn">Delete</button></a>
                            </form>
                        </div>
                    </div>
                </li>
                <hr>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<script>
    var icon = document.querySelector('.icono');
    var keys = Object.keys(window.localStorage);
    var postsLiked = [];
    keys.forEach(key => {
        postsLiked.push(JSON.parse(window.localStorage.getItem(key)));
    });

    icon.addEventListener('click', () => {
        window.localStorage.setItem("{{post.title}}", JSON.stringify({
            post: "{{post.id}}",
            liked: true
        }));
    });

    postsLiked.forEach(post => {
        if (post.post === "{{post.id}}") {
            if (post.liked) {
                icon.addEventListener('click', () => {
                    console.log('soy verdadero y tengo like');
                    document.querySelector('.icon-link').href =
                        "{% url 'blog:reduce_like' pk=post.pk %}";
                    window.localStorage.setItem("{{post.title}}", JSON.stringify({
                        post: "{{post.id}}",
                        liked: false
                    }));
                });
            } else {
                icon.addEventListener('click', () => {
                    console.log('soy falso y no estoy likeado');
                    icon.className = "heart-icon icono icon-heart-empty";
                    window.localStorage.setItem("{{post.title}}", JSON.stringify({
                        post: "{{post.id}}",
                        liked: true
                    }));
                });
            }
        }

    });

    postsLiked.forEach(post => {
        if (post.post === "{{post.id}}") {
            if (post.liked === true) {
                icon.className = "heart-icon icono icon-heart";
            } else {

                icon.className = "heart-icon icono icon-heart-empty";
            }
        }
    });
</script>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>New Post</h1>
            <form action="" method="POST">
                {%csrf_token%}
                {{ form.as_p }}
                <input type="submit" class="btn btn-save" value="Save">
            </form>
            <a href="{% url 'blog:post_list' %}" class="btn btn-save mt-3 ">Cancel</a>
        </div>
    </div>
</div>
{% load static %}
<script src="{% static 'js/medium-editor.js' %}"></script>
<script src="{% static 'js/medium-button.min.js' %}"></script>
<!-- <script>
    var editor = new MediumEditor('.editable', {
        toolbar: {
            buttons: ['bold', 'italic', 'underline', 'anchor', 'h4', 'h3', 'quote', 'code', 'gist']
        },
        extensions: {
            // compact
            'code': new MediumButton({
                label: 'code',
                start: '<pre><code>',
                end: '</code></pre>'
            })
        }
    });
</script> -->
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<div class="container">
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col">
            <a href="{% url 'blog:new_post' %}" class="newposticon"><i class="icon-plus"></i><strong>New
                    Post</strong></a>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="content col-12 col-lg-9 posts">
            {% for post in post_list %}
            <div class="card my-3">
                <div class="card-body">
                    <div class="container">
                        <div class="row">
                            <!-- <div class="col-2">
                                <img class="img-fluid rounded-circle img-thumbnail" src="{% static 'img/paul.jpg' %}"
                                    alt="">
                            </div> -->
                            <div class="col-12">
                                <a href="{% url 'blog:post_detail'  pk=post.pk%}" class="card_title_link">
                                    <h1 class="mb-3 card-title">{{post.title}}</h1>
                                </a>
                                <div class="row">
                                    <div class="col d-inline-flex">
                                        <p><span><img src="{% static 'img/paul.jpg' %}" class="profile_picture"
                                                    width="30px" height="30px" alt="" foto></span> {{post.author}}</p>
                                        <i class="icon-dot"></i>
                                        <p>{{post.created_date}}</p>
                                    </div>
                                </div>
                                <p>
                                    {% for tag in post.split_tags %}
                                    <a href="#" class="badge badge-light">{{tag}}</a>
                                    {% endfor %}
                                </p>
                                <div class="text-right  likes_and_comments">
                                    {{post.comments.count}}
                                    <i class="icon-commenting-o comments-icon"></i>
                                    {{post.likes}}
                                    <i class="icon-heart-empty like-icon"></i>
                                    {% if user.is_authenticated is True %}
                                    {% if post.highlight %}
                                    <a href="{% url 'blog:remove_highlight' pk=post.pk %}"><i class="icon-star"></i></a>
                                    {% elif post.highlight is False %}
                                    <a href="{% url 'blog:highlight_post' pk=post.pk %}"><i
                                            class="icon-star-empty"></i></a>
                                    {% endif %}

                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="sidebar col-12 col-lg-3">
            <div class="card my-3">
                <div class="card-body text-center">
                    <h4>Highlighted Posts</h4>
                    {% for post in post_list %}
                    {% if post.highlight == True %}
                    <p><a href="{% url 'blog:post_detail'  pk=post.pk%}" class="most-liked-posts">{{post.title}}</a></p>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="card my-3">
                <div class="card-body text-center">
                    <h4>Most Liked Posts</h4>
                    {% for post in post_list %}
                    {% if post.likes > 4 %}
                    <p><a href="{% url 'blog:post_detail'  pk=post.pk%}" class="most-liked-posts">{{post.title}}</a></p>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Paul Miranda Vega</title>
    <link rel="icon" href="{% static 'img/paul-logo.png' %}">
    <!-- <link rel="stylesheet" href="{% static 'dist/css/medium-editor.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/themes/beagle.css' %}"> -->
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
            <a class="navbar-brand" href="{% url 'blog:post_list' %}">
                <img src="{% static 'img/paul-logo.png' %}" width="30" height="30" alt="logo">
                Paul Miranda
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active d-inline-flex align-items-center">
                        <i class="icon-home"></i>
                        <a class="nav-link" href="{% url 'blog:post_list' %}">Home <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item d-inline-flex align-items-center">
                        <i class="icon-male"></i>
                        <a class="nav-link" href="{% url 'aboutme:aboutme' %}">About Me</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">
                    <button class="btn log">Logout</button>
                </a>
                {% else %}
                <a href="{% url 'login' %}">
                    <button class="btn log">Login</button>
                </a>
                {% endif %}

            </div>

        </nav>
    </header>

    <main>
        {% block body_block %}
        {% endblock %}
    </main>

    <footer class="footer mt-auto py-3">
        <div class="container text-center" style="color:white;">
            Paul Miranda Vega
        </div>
    </footer>
</body>
<!-- <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script> -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script>
    var navitems = document.getElementsByClassName("nav-item");
    for (var i = 0; i < navitems.length; i++) {
        navitems[i].addEventListener("click", function () {
            var current = document.getElementsByClassName("active");
            current[0].className = current[0].className.replace(" active", "");
            this.className += " active";
        });
    }
</script>

</html>